device: "cuda"
total_epochs: 10
episodes_per_epoch: 5
update_frequency: 3
eval_episodes: 2
save_frequency: 2

output_dir: "/content/drive/MyDrive/agentworkflow/outputs/minimal_test"
experience_pool_size: 1000

environment:
  train_datasets:
    - "AIME"
  test_datasets:
    - "AIME"
  data_path: "/content/agentworkflow/AFlow/data/AIME_2024.jsonl"

  opt_llm_config:
    model: "gpt-4o-mini"
    key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    temperature: 0.9

  exec_llm_config:
    model: "gpt-4o-mini"
    key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    temperature: 0.8

  operators:
    - "Custom"
    - "MathSolver"
    - "WebSearch"
    - "ScEnsemble"
    - "Test"
    - "Review"
    - "Rephrase"

  env_num: 1
  group_n: 1
  max_rounds: 10
  validation_rounds: 6
  sample: 12  # 测试 12 个问题以获得真实的 pass@12

rl:
  policy:
    model_path: "/root/models/Qwen2.5-7B-Instruct"
    use_lora: true
    lora_r: 16
    lora_alpha: 32
    value_head_dim: 1024

  learning_rate: 0.0001
  batch_size: 16
  ppo_epochs: 4
  ppo_clip: 0.2
  gamma: 0.99
  gae_lambda: 0.95
  value_coef: 0.5
  entropy_coef: 0.05
  gradient_clip: 1.0

  gigpo:
    enable: true
    epsilon: 0.000001
    step_advantage_w: 0.8
    mode: "mean_norm"
    enable_similarity: true

logging:
  level: "INFO"

debug:
  verbose_env: true
